version: "3"
services: 
  app:
    api-server
    build: ./
    env_file: ./config/config.env
    ports: 
      - 3000:3000
    networks: 
      - storybooks-app
    depends_on: 
      - mongo

  mongo:
    image: mongo:latest
    environment: 
      - MONGO_INITB_DATABASE=storybooks
    ports: 
      - 27017:27017

  networks:
    storybooks-app:
      driver: bridge


  volumes: 
    mongo-data:
      driver: local

